ci: test start mase failure

diff --git a/.github/workflows/node-build.yml b/.github/workflows/node-build.yml
--- a/.github/workflows/node-build.yml
+++ b/.github/workflows/node-build.yml
@@ -196,11 +196,20 @@ jobs:
         id: perf_test
         run: |
           pnpm --filter performance run-tests:testenv -k -q --vus 4 --duration 1m | tee performance.log
-        continue-on-error: true # Don't fail here, allows showing logs
+          if [ $? -ne 0 ]; then
+            echo "Performance tests failed. Output:"
+            cat performance.log
+            exit 1
+          else
+            echo "Performance tests passed."
+          fi
 
-      - name: Print MASE logs
-        if: always()
-        run: cat mases.log
+      # - name: Print MASE logs
+      #   if: failure()
+      #   run: |
+      #     echo "Run performance tests errored."
+      #     cat mases.log
+      #     exit 1
 
       - name: Post/Update Performance Test Results as PR Comment
         if: always()
@@ -281,9 +290,9 @@ jobs:
               console.log("No PR detected, skipping comment.");
             }
 
-      - name: Fail if performance tests failed
-        if: steps.perf_test.outcome == 'failure'
-        run: exit 1
+      # - name: Fail if performance tests failed
+      #   if: steps.perf_test.outcome == 'failure'
+      #   run: exit 1
 
 
 
