ci: test start mase failure

diff --git a/.github/workflows/node-build.yml b/.github/workflows/node-build.yml
--- a/.github/workflows/node-build.yml
+++ b/.github/workflows/node-build.yml
@@ -196,14 +196,11 @@ jobs:
         id: perf_test
         run: |
           pnpm --filter performance run-tests:testenv -k -q --vus 4 --duration 1m | tee performance.log
-          exit_code=${PIPESTATUS[0]}
-          if [ $exit_code -ne 0 ]; then
-            echo "Performance tests failed. Output:"
-            cat mases.log
-            exit 1
-          else
-            echo "Performance tests passed."
-          fi
+        continue-on-error: true # Don't fail here, allows showing logs
+
+      - name: Print MASE logs
+        if: always()
+        run: cat mases.log
 
       - name: Post/Update Performance Test Results as PR Comment
         if: always()
@@ -283,6 +280,10 @@ jobs:
             } else {
               console.log("No PR detected, skipping comment.");
             }
+
+      - name: Fail if performance tests failed
+        if: steps.perf_test.outcome == 'failure'
+        run: exit 1
 
   node-build:
     runs-on: ubuntu-latest
