chore: debug test in ci

diff --git a/.github/workflows/node-build.yml b/.github/workflows/node-build.yml
--- a/.github/workflows/node-build.yml
+++ b/.github/workflows/node-build.yml
@@ -193,12 +193,17 @@ jobs:
         run: nohup pnpm --filter performance start-mases > mases.log 2>&1 &
 
       - name: Run performance tests
+        id: perf_test
         run: pnpm --filter performance run-tests:testenv
-        continue-on-error: true
+        continue-on-error: true # Dont fail here, allows showing logs
 
       - name: Print MASE logs
         if: always()
         run: cat mases.log
+
+      - name: Fail if performance tests failed
+        if: steps.perf_test.outcome == 'failure'
+        run: exit 1
 
   node-build:
     runs-on: ubuntu-latest
